import "./globals.css";
import { Montserrat } from "next/font/google";

import Navbar from "./components/Navbar";
export const metadata = {
  title: "Movie Next App",
  description: "Generated by create next app",
};

const mont = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "mont",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mont.className} mx-32 my-7`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
