import "./globals.css";
import { Montserrat } from "next/font/google";
import Link from "next/link";
export const metadata = {
  title: "Movie Next App",
  description: "Generated by create next app",
};

const mont = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "mont",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mont.className} mx-32 my-12`}>
        <nav className="flex items-center justify-between mb-5">
          <h1 className="font-[700] flex text-2xl">The Movies App</h1>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
